type Band {
  id: ID!
  name: String
  origin: String
  members: [Member]
  website: String
  genres: String
}

input BandInput {
  name: String!
  origin: String
  website: String
  genres: String
}

type Query {
  band(id: ID!): Band
  bands: [Band]
}

type deleteBand {
  acknowledged: Boolean!
  deletedCount: Int
}

type Mutation {
  createBand(name: String!, origin: String, members: MemberInput, website: String, genres: String): Band
  updateBand(id: ID!, name: String, origin: String, members: MemberInput, website: String, genres: String): Band
  deleteBand(id: ID!): deleteBand
}